### ISSUE TITLE
Suggestion: Regarding ingredients

### ISSUE THREAD

**Issue by GreyMoth** [nanawel/reciphpes#29]
In order for the ingredients tab to be more useful, I think there should be a separate entry when adding an ingredient for quantity.
Example: 1 tsp olive oil
Example: 1 cup of basil, chopped (chopped would go in the notes section)
On the ingredients tab, each of these will register as a separate entry, which makes the ingredient page less useful.

Alternatively, you might consider removing the ingredients page altogether, in favor of using the already included search function. (Although slightly modified to encompass ingredients as part of recipes in search results)

Again-- just suggestions

**Comment by nanawel** [comment]
Sorry for the delay and thanks for your suggestion.
This behavior is intentional, I just don't want to have too many fields to fill in when writing a recipe. Of course there could be much a more precise and detailed way to do, but the current way is a compromise that suits my needs.

Sorry :confused:
